apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ukf-pv-claim
  namespace: ukf
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
