apiVersion: v1
kind: Service
metadata:
  name: php-nginx-service
  namespace: ukf
spec:
  selector:
    app: php-nginx-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
