apiVersion: v1
kind: Service
metadata:
  name: apache-php-service
  namespace: ukf
spec:
  selector:
    app: apache-php
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 
